GET http://localhost:8000/api/noticias
Accept: application/json
Authorization: Bearer 7|KciJzBTAcRgTHzCuL83Pi6tvDzMzo49qKxLZo9XB

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "name": "Sthefany Kimberly",
    "email": "sthefanykmbrl@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:8000/api/noticias/1
Accept: application/json
Authorization: Bearer 7|KciJzBTAcRgTHzCuL83Pi6tvDzMzo49qKxLZo9XB

###
POST http://localhost:8000/api/noticias
Authorization: Bearer 7|KciJzBTAcRgTHzCuL83Pi6tvDzMzo49qKxLZo9XB
Content-Type: application/json
Accept: application/json

{
    "titulo": "TITULO NOTICIA 3",
    "descricao": "DESCRICAO NOTICIA 3",
    "user_id": 3
}

###
PUT http://localhost:8000/api/noticias/3
Accept: application/json
Authorization: Bearer 3|4n9oBxwPMbSqizDfp2WbItXfmhzhxXKk9RBsJ1Vt
Content-Type: application/json

{
    "titulo": "TITULO NOTICIA 5",
    "descricao": "DESCRICAO NOTICIA 5",
    "user_id": 5
}

###
PATCH http://localhost:8000/api/noticias/3
Accept: application/json
Authorization: Bearer 3|4n9oBxwPMbSqizDfp2WbItXfmhzhxXKk9RBsJ1Vt
Content-Type: application/json

{
    "titulo": "TITULO NOTICIA 4",
    "user_id": 5
}

###
DELETE http://localhost:8000/api/noticias/5
Accept: application/json
Authorization: Bearer 11|nC6POeBh40qidOIiGaPu5Fq6QflFTq7DzzcGS3ax

